name: Generate Release

# generate release for tagged commits on default branch
on:
  push:
    branches:
      - bl_28
    tags:
      - "luv.[0-9]+.[0-9]+.[0-9]+*"


# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Add a release, and include a zip file
  latest-release:
    name: Latest Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Zip
        run: |
          zip -r Blender-CM3D2-Converter.zip "CM3D2 Converter"
      - name: Draft Tagged Release
        if: ${{ github.ref_type == 'tag' }}
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: true
          CHANGELOG_FILE: none
          TAG_PREFIX_REGEX: luv.
        with:
          args: Blender-CM3D2-Converter.zip
      - name: Draft Untagged Release
        if: ${{ github.ref_type == 'branch' }}
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: true
          CHANGELOG_FILE: none
          UNRELEASED: "update"
        with:
          args: Blender-CM3D2-Converter.zip
            
