name: Generate Release

# generate release for tagged commits on default branch
on:
  push:
    #branches:
    #  - bl_28
    #tags:
    #  - "luv\\.[0-9]+\\.[0-9]+\\.[0-9]+*"


# security: restrict permissions for CI jobs.
permissions:
  contents: write

jobs:
  # Add a release, and include a zip file
  latest-release:
    name: Latest Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Determine Tagged Zip Name
        if: ${{ github.ref_type == 'tag' }}
        run: |
          VERSION_SUFFIX=$(echo ${{github.ref_name}} | awk '{gsub("\\.","-")}1')
          echo ZIP_FILE="Blender-CM3D2-Converter-bl_28.$VERSION_SUFFIX.zip" >> $GITHUB_ENV
      - name: Determine Untagged Zip Name
        if: ${{ github.ref_type == 'branch' }}
        run: |
          VERSION_SUFFIX=$(echo ${{github.sha}} | cut -c 1-7)
          echo ZIP_FILE="Blender-CM3D2-Converter-bl_28.${{github.sha}}.zip" >> $GITHUB_ENV
      - name: Create Zip
        run: |
          zip -r ${{env.ZIP_FILE}} "CM3D2 Converter"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ZIP_FILE }}
          path: ${{ env.ZIP_FILE }}
      - name: Draft Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.ZIP_FILE }}
          draft: true
          generateReleaseNotes: true
            
