name: Generate Release

# generate release for tagged commits on default branch
on:
  push:
    branches:
      - bl_28
    tags:
      - "luv.[0-9]+.[0-9]+.[0-9]+*"


# security: restrict permissions for CI jobs.
permissions:
  contents: write

jobs:
  # Add a release, and include a zip file
  latest-release:
    name: Latest Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Determine Tagged Zip Name
        if: ${{ github.ref_type == 'tag' }}
        run: |
          VERSION_SUFFIX=$(echo ${{github.ref_name}} | awk '{gsub("\\.","-")}1')
          export ZIP_FILE="Blender-CM3D2-Converter-bl_28.$VERSION_SUFFIX.zip"
      - name: Determine Untagged Zip Name
        if: ${{ github.ref_type == 'branch' }}
        run: |
          VERSION_SUFFIX=$(echo ${{github.sha}} | cut -c 1-7)
          export ZIP_FILE="Blender-CM3D2-Converter-bl_28.${{github.sha}}.zip"
      - name: Create Zip
        run: |
          zip -r $ZIP_FILE "CM3D2 Converter"
      - name: Draft Tagged Release
        if: ${{ github.ref_type == 'tag' }}
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: true
          CHANGELOG_FILE: none
          TAG_PREFIX_REGEX: luv.
        with:
          args: Blender-CM3D2-Converter.zip
      - name: Draft Untagged Release
        if: ${{ github.ref_type == 'branch' }}
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: true
          CHANGELOG_FILE: none
          UNRELEASED: "update"
        with:
          args: Blender-CM3D2-Converter.zip
            
